project:
  type: website
  output-dir: _site
  preview: 
    port: 4200
  resources:
    - "*.pdf"

website:
  title: "JeradXYZ"
## TODO host site on netlify - use github repo
  site-url: https://jerad.xyz/
  comments: 
    utterances:
      repo: irJERAD/JeradXYZ
## TODO: Create an add favicon - use vectornator
#  favicon: 
  navbar:
    right:
      - text: "Posts"
        href: posts.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Certifications"
        href: certifications.qmd
      - text: "About"
        href: about.qmd
        
format:
  html:
    theme: slate
    css: styles.css

editor: visual

