project:
  type: website
  output-dir: _site
  preview: 
    port: 4200
  resources:
    - "*.pdf"

website:
  title: "JeradXYZ"
  site-url: https://jerad.xyz/
  # comments: 
  #   utterances:
  #     repo: 
## TODO: Create an add favicon
#  favicon: 
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Posts"
        href: posts.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Certifications"
        href: certifications.qmd
        
format:
  html:
    theme: slate
    css: styles.css

editor: visual

