---
title: "Systematically Reducing Stress While Accomplishing More"
author: Jerad Acosta
---

Anxiety paralysis is real. And it has got me by the neck at times. Quite often I would say.

My life wreaks of devastation in clear patterns across time and area. A devistation that reads: "I wanted to do it, I definitely started to do it - many times in-fact, ..." but the end is always the same "I did not do it".

These hurt. Finding yourself with so many unfinished projects, items on the todo list, or worse, responsibilities that in this familiar destruction, you left someone you care about hanging.
You are packed with excuses, and are quick to share heart warming facts you hope provide them with whatever it takes to compose a reasonable cause for your failure to, well, to *do*.

TODO:
- continue with this story, relatable, emphathy from readers part later

Get into the process:

In a recent fit of burning inspiration I channeled my episodic fountain of pure and passionate effort into what I would like to share here, now.
For you? Well, it is nice to imagine you are there and engaged in my ramblings but this is for me. And dont take it personal, I would recommend, no insist, that any attempts at trying this on for size include the explorer doing an abreviated - and far more focused - version of this very piece.

Ok... again, on with the actual sustinance ...

## Breakdown

Think for a moment about all your projects, on-going, planned, and temporarily paused (but totally getting right back to it - right?).

This is for individuals who have an issue with anxiety. Like the kind that stops you from being able to do stuff. That makes even discussing the fact that you are behind or having scheduling issues feel like you are asking yourself to mount Olympus.

Yes for me.

Break them into three main groups

### Group 1: Causing you anxiety this very moment
At any given time I can be managing one to two healthy handfuls of items on my todo list that are causing me a discomforting level of anxiety.  

So much, it is not uncommon that I find myself stuck inside a self imposed detention. Unable to leave the bed due to the physical experience of anxiety. Even if I manage the overcome the physical impediment, the mental anguish of my inner narrative intimidates me back into my shell.  

Serial episodes of why I am not capable of doing what I already committed myself to - and because I so excitedly and honestly, more accurately, knew I was capable of.  

Play back-to-back against commercials of my impotence in even starting what I know will take a few minutes when I am on - even in a bad state-of-mind things don't take more that a honest efforts time to life out the ego fueling experience of taking on and accomplishing something you set out to.  
Because, in truth, most the things I set out to do I am quite excited to do. I mean it, I love accomplishing the kinds of things I publicize myself as to myself and to others.
(I find the origin of these unfinished tasks that haunt me)

## Group 2: Items that will cause future anxiety. Particularly if you take your usual course of avoiding and making yourself susceptible to this process.

## Group 3: TODO items that build potential. For me, this includes any of the myriad projects, portfolio buildings, and "some day" apps I hope to build. All of these challenges open new skills for me to explore. New professional avenues avail themselves when I participate in these treasured "you know what would be cool?" ideas poised as a task added to my someday list.

## Prioritization of tasks:  

1. We start at the root! Take on the items causing you pain and discomfort now. This sounds obvious, but based on personal experience I can attest to how seldom this is practiced. The inspiration I experience when I find myself in excess of both motivation and time.  

1.1. Note: Give yourself a small handful of quick tasks in this category. The pride in self you experience will get you more pumped then when you started the exercise.  

2. If you are making progress it is OK to endulge in a couple tasks that are categorized in the *will* cause anxiety and discomfort if you don't finsih them up sooner than later.  
I find myself jumping to these, likely because it creates the illusion of being more productive than you are - accomplishing things not due yet.
Or more likely, cherry picking tasks that, for whatever reason, just don't rub you as wrong as the first group.

3. Finally, if you stick to this system you will find yourself burning with a lot less anxiety and a lot more enthusiasm to take on some cool stuff. This is the time for the third group. 

This has the added benefit of getting to work on passion projects when you will actually complete them. I often use them to feel better or be busy when you are hurting from the knowledge that you have something you are supposed to be doing.

Put passion in its place - a place that opens doors and unviels new opporunities and perspective in life.

Enjoy it! Don't endure it.