---
title: "Understand The Need Around You."
date: 2023-03-21
---


How often we may find ourself inhabiting the same place. 
Doing that everyday task. 
And then running off to your typical local.

And then there are times we see something special. 
Or, is it, the missing of something special or some special place. 

Did you reach out to place down your cup of coffee, only to hear it shatter upon the floor at your toes.
The corner table or bar you had envisioned so perfectly in your minds eye had no such place in the physical world. 

What about when you reach out, across the table to palm the keys, only to find you have copped a tangle of loose paperclips jammed between your fingers.


We inhabit so many ingeniously designed environments with natural grace at a pace of location to location. 
Each within arms reach of an arms reach.
This can result in some fascinating experiences of cognitive dissonance,  while we the being, act as though an expected location or item lay there in its entirety as well as interact with all governing appendages through natural and causally expected laws of mechanics.




