---
title: "Jerad's spring 2023 goals"
date: 20-04-2023
draft: false
---

This page will serve to host my spring 2023 goals. Inspired - as I often find myself while I walk this [beautiful city](https://en.wikipedia.org/wiki/Auckland) - I took out my iPhone, and opened up the Reminders app to create an interim home.

For the rest of the walk my desires would take shape

## Goal List:

1)  Become a more reliable individual

2)  Live less burdened with anxiety

3)  Stay away from the seduction of sloth

4)  Aim to become a far greater conduit of understanding and forecasting with regard to receiving information and signs as to what you should do and where you should be doing

    -   Better said: keep your ears to the ground and act when you hear the wind calling your name

### Become a more reliable individual

### Live less burdened with anxiety

### Stay away from the seduction of sloth

### Keep your ears to the ground and act when you hear the wind calling your name

Over the past few months I have experienced the most unexpected boon to my life. The fortune filled me with anticipation for lay ahead. My time is spent with my wife, Stephanie, in our beautiful home in [Punaauia, Tahiti](https://en.wikipedia.org/wiki/Punaauia). Only 200 meters from our parents home, we enjoy breakfast, lunch, and dinner together as a family every day. Steph's father is an impressive chef with a recipe collection capable of bringing out the glutton in me.

Two days each week I enjoy spending a quick 40 minutes with the students I work with in San Francisco. Whether covering new material, reviewing problems, or discussing our goals outside and beyond high school, I have found some of my most fulfilling moments with these children.

Each time I recount my first visit to [Eglise Bonne Nouvelle](https://www.facebook.com/egliselabonnenouvellefaaa) in [Faʻaʻā](https://en.wikipedia.org/wiki/Fa%CA%BBa%CA%BB%C4%81), I trip out or get goose bumps and feel filled with purpose and potential. I came on the invitation of the only other couple I could speak English with - outside my immediate family that is.

I had been suffering from a strange type of loneliness. I lived with my wife and we stayed home most days together. We would join our parents down the street for breakfast, lunch, and dinner each and everyday. French was the language necessary to navigate butter and bread across our table. I was afforded the occasional courteous English commands. And fun idioms where anyone's game to say, and then, for me, explain.

Unknowingly, at first, the symptoms of this strange loneliness would take hold in dormant areas of my psyche. Keeping to ourselves by custom, I did not interact with many people outside our household. While rousing when passing neighbors and the like, the lack of a shared tongue rendered me incapable of experiencing any depth in human interaction.

Along come Marc and Jo - the friendly hosts of [English Speakers in Tahit](https://www.facebook.com/groups/274544326409290)

They took me on a trail that went just the right amount further than I was comfortable hiking, pointing out some of French Polynesia's treasures. Atop the mountain I was gifted a view of Punaauia's legendary orange tree fields.

After our hike together a newly acquainted friend shared some juice with us as we talked a little more about ourselves. I found a friend in Jo a skateboarder who was [*"keen"*]{.underline} to take me downtown to shred the local park.

Marc and Jo were also excited to show me their local church. The Sunday I met them their is what this article was supposed to be about!

I enjoyed a worship
