---
title: "Meditate on a Love for Learning"
author: "Jerad Acosta"
date: "2022-07-28"
categories: [education,self,appreciation,love]
---

At the age of 12 I was almost held back in school. During a parent-teacher conference my mother and step-father had been under a barrage of scathing remarks regarding my performance in school that year. I had been close to or failing nearly all my classes. I would, they had determined, repeat the sixth grade.

That was, until my math teacher at the time stood up gesturing he had heard enough and said:

> "This is ridiculous. The boy is obviously brilliant and should not be held back on account of our inability to reach him"

You see, I did not pay attention during class and I did not do homework *at all* - paired with some minor dyslexia and early symptoms of ADD - **I was a horrible student**. I did, however, LOVE our take home challenges we were given during math class. Designed to tease our sense of intuition and provoke a desire to solve something so revered it lay written along the side of the board calling out anyone who dare solve it.

In fact, I became so successful at these problems, my teacher drafted me to join the Mathletes - despite my appalling grades. It was this relationship, which then grew to include chess and competitive chess, that endeared me to this professor. And fortunately so because it was this familiarity which enabled him to stand up for me.

After this debacle, it was clear something needed to change. This is when I began to take ownership of my own education. Something clicked in me. It became clear that academics was not the responsibility of my teachers, nor my parents, nor anyone other than myself.

### So I decided I would Love School

The strategy that had the greatest impact on me was rather straight forward: Love School. Loving school was like self-selecting myself to become a nerd. But in order for this to work I had to *fall* in love with school first.

#### Fake it 'til You Make it

After school, before faced with and whenever procrastinating the start of homework, I talk to myself.

> "I ***love*** school. I **LOVE** Math. History is ***so*** interesting..."

Now when I work with students I advise them to take that minute between sitting down in class and when the teacher starts talking to meditate. Focus your attention inward. Take time to appreciate just where you are and what you are doing. [Appreciate you educational opportunity](/posts/appreciation-of-our-educational-opportunity). Recite the mantra:

> "I ***love*** this class. I am ***so*** lucky to be here. **I am grateful** for my teacher"  

### Conclusion  

See how far intentional love and affectionate appreciation take you in your personal path through education.  