---
title: "An Appreciation of Our Educational Opportunity"
author: "Jerad Acosta"
date: "2022-07-28"
categories: [education,self,appreciation]
---

As early as many of us can remember we have been asked a simple question:

> "What would you like to be when you grow up?"

This simple question says a lot about us as a society.  

For one, how incredibly self-lead we must be! I mean, we are asking 4 and 5 year olds to provide introspective and existential information on the where and what-abouts of their future, both near and far.  

It was not so long ago - in our relative history as a species - where one was simply born into a future; the one currently held by their parents. The son's of farmers would grow up working the land with their family to become farmers themselves. The offspring of tradesmen had their cast iron future - son of a blacksmith would grow up to study and become a blacksmith. And the fortunate sons of merchants had their lot in life set afront of them before they could begin to walk it.  

Perhaps the most diverse set of future possibilities belonged to the young women of the past. For they could become the wives of whom ever was so arranged to be their husband. That, however, just does not hold up to the expectations and perceived rights of the future for today's young women.